### ISSUE TITLE
АвтоБЕНДЕР или В помощь преподавателям ;)

### ISSUE THREAD

**Issue by Vetnametz** [OlegPasko/rorgh#3]
День добрый!
В первую очередь хочу сказать спасибо Олегу за возможность работать с группой. Это клево, что можно проходить несколько курсов.
Второе, предлагаю на рассмотрение Олега вариант сдачи ДЗ.
Вариант достаточно простой, возможность пропустить через некоего автоБендера код ДЗ. Если все тестовые проходит, синтаксис без ошибок и блаблабла ... знач зачет ДЗ.
Думаю это позволит освободить преподавателя от рутинной проверки/просмотра ДЗ всех слушателей.

**Comment by OlegPasko** [comment]
Спасибо, отличная идея!
Вот только кто бы взялся ща автоБендера? )) На отсутствие ошибок проверить просто, а на результат и на не очень хороший код?

**Comment by sergiy-koshoviy** [comment]
Задумка цікава але і має деякі криві сторони.
- знизиться ефективність звязку викладач-студент
- автоБЕНДЕР не розбере ідею коду яку хотів викласти автор.

тож це хіба що як перша ступінь яка допоможе відсіяти ну дуже хреново зроблені ДЗ.
Сподіваюсь таких у нас не буде ))))
