### ISSUE TITLE
Аватарки_Смайлики.

### ISSUE THREAD

**Issue by sergiy-koshoviy** [OlegPasko/rorgh#4]
Не мега корисна, але з ними цікавіше.(як на мене :) ), о точно і смайлики...куди ж без них..

**Comment by OlegPasko** [comment]
8b9d4c6a9c47550dd076756534ab7505c90fa9c9
Граватарки есть, а вот смайлики, вероятно, совсем на потом )

**Comment by sergiy-koshoviy** [comment]
хі-хі-хі, значить згадуємо поки що ASCII-графіку. (^_^)
