### ISSUE TITLE
Названия дз

### ISSUE THREAD

**Issue by xandrck** [OlegPasko/rorgh#8]
Понимаю по айдишникам проще чтобы не путаться, но может лучше будет задания как-то обзывать, а айдишники использовать для номера занятия к примеру, чтобы была так сказать какая-то иерархия.

Например:
  1.бабушка
  2.бабушка

**Comment by sergiy-koshoviy** [comment]
не має значення так як нові завдання будуть створюватись в новому каталозі. а в назва цього каталогу буде відповідати темі завдань так би мовити. а там вже не так і багато завдань буде щоб заплутатись.
