### ISSUE TITLE
Комментарии, код

### ISSUE THREAD

**Issue by xandrck** [OlegPasko/rorgh#9]
Было бы неплохо, в будущем думаю понадобиться, использовать какое-то выделение для кода.

Что-то типа такого http://en.wikipedia.org/wiki/Markdown

**Comment by OlegPasko** [comment]
Есть :) &#60;code&#62; — для строки или &#60;pre&#62; для фрагмента
Вот тут есть как раз пример использования: http://muschool.org/posts/3
